// BLUEPRINT LAYER - composed, launchable projects.
// The category is the anchor. Typed classification is ONE capability inside a larger build.
// Each blueprint: the job, who it is for, the capability stack, the build phases,
// which shipped evidence proves each risky part, and what actually goes wrong.

export const BLUEPRINTS = [
  {
    id: "fit-finder",
    category: "commerce",
    name: "Fit Finder for hard-to-fit bodies",
    jtbd: "When I am outside the sizes shops design for, I want to know which specific garment will actually fit me, so I stop ordering three sizes and returning two.",
    who: "Shoppers at the edges of the size curve. Plus-size, tall, petite, asymmetric, post-surgery.",
    why_now: "Every brand publishes a different size chart and none of them agree. That is a normalisation problem, and normalisation at catalogue scale is exactly what a cheap typed judgment is for.",
    stack: ["fetch", "classify", "vision", "search", "imagegen", "voicein", "store", "orchestrate"],
    jev_role: "Normalises each garment against a body profile: cut, stretch, rise, shoulder slope, and a fit verdict with a confidence number. One typed call per garment.",
    not_jev: "Catalogue scraping, size-chart OCR, the try-on render, and the shop front are all ordinary engineering. Jev is maybe 10% of the code.",
    phases: [
      { n: 1, name: "Corpus", detail: "Scrape 3-5 brands. Look for an embedded JSON blob before you render anything. Store garment, size chart, fabric, and the product image.", caps: ["fetch", "store"] },
      { n: 2, name: "Normalise", detail: "Size charts are images and inconsistent tables. OCR them into one schema: chest, waist, hip, inseam, stretch percentage.", caps: ["vision"] },
      { n: 3, name: "Judge", detail: "One typed call per garment against the body profile. Choice for fit verdict, Score for confidence in each dimension, Noul for the dealbreakers.", caps: ["classify"] },
      { n: 4, name: "Rank", detail: "Retrieve wide with filters, then order the shortlist by the typed score. Never score the whole catalogue live.", caps: ["search"] },
      { n: 5, name: "Try on", detail: "Render the top few garments on the body. Strictly off the critical path - precompute or stream it.", caps: ["imagegen"] },
      { n: 6, name: "Ask out loud", detail: "Voice input for the profile. Speaking measurements beats typing them on a phone.", caps: ["voicein"] },
    ],
    evidence: ["EasyFinder intent-based product filters", "Scoring 3,000 kids’ snacks", "Hipershopping with Agentcard", "OCR-powered image classification"],
    hard_parts: [
      "Size charts are pictures, not data. OCR quality decides the whole product.",
      "Try-on rendering is 2-30s. Put it behind the ranked list, never in front of it.",
      "A wrong fit verdict costs a return, so gate on confidence and say 'unsure' out loud.",
    ],
    effort: 4, impact: 5,
    moat: "The normalised size-chart corpus. The model is rentable; the corpus is not.",
  },
  {
    id: "curriculum-factory",
    category: "education",
    name: "Curriculum content factory for every class",
    jtbd: "When I teach or study a syllabus, I want every section rendered in several study modes with a grounded tutor, so a student can revise the way that suits them without me authoring it five times.",
    who: "Ed-tech builders, teachers, and anyone turning a public syllabus into a study product.",
    why_now: "The gallery has exactly ONE education project out of 359. The category is empty while the capability is ready.",
    stack: ["fetch", "vision", "classify", "textgen", "imagegen", "store", "orchestrate", "guardrail"],
    jev_role: "Every quality gate and routing decision. Is this section complete, is this question answerable from the source, which difficulty tier, is this glossary term depictable, does this answer stray off-syllabus.",
    not_jev: "PDF to markdown, the authoring model, image generation, the reader UI, and the tutor chat are the bulk of the build.",
    phases: [
      { n: 1, name: "Source", detail: "Official chapter PDFs to clean markdown with a real text layer. OCR only where you must.", caps: ["fetch", "vision"] },
      { n: 2, name: "Author", detail: "A strong model reproduces the canonical text faithfully. This is the one place to spend real tokens.", caps: ["textgen"] },
      { n: 3, name: "Gate", detail: "Typed checks per section: coverage, factual traceability, equation balance. All checks ride in ONE call.", caps: ["classify", "guardrail"] },
      { n: 4, name: "Derive modes", detail: "Cards, flashcards, graded questions and a glossary, all derived from the canonical text, never re-authored.", caps: ["textgen", "classify"] },
      { n: 5, name: "Illustrate", detail: "Typed call decides which terms are depictable at all, then generate only those. Skip the rest.", caps: ["classify", "imagegen"] },
      { n: 6, name: "Ground the tutor", detail: "The chatbot answers only from the active section. A typed call detects off-topic and redirects.", caps: ["classify", "guardrail"] },
    ],
    evidence: ["TC39 Atlas", "A draft quality gate", "Fourteen checks for every pull request", "Sentence-by-sentence AI text detection"],
    hard_parts: [
      "Faithfulness beats fluency. A confident wrong equation is worse than no content.",
      "Image generation is the pole. Precompute it off the critical path or a chapter takes twenty minutes instead of three.",
      "Rate limits, not cost, cap throughput at about 20 typed calls a second.",
    ],
    effort: 4, impact: 5,
    moat: "The derived, quality-gated corpus per chapter. Re-deriving is cheap; the gates are the asset.",
  },
  {
    id: "label-scanner",
    category: "food",
    name: "Back-of-label scanner and scorer",
    jtbd: "When I pick up a packaged food, I want to know in one second whether it clears my household rules, so I can decide in the aisle.",
    who: "Parents, people with allergies, anyone on a medical diet.",
    why_now: "One shipped project scored 3,000 snacks on multiple criteria in 28 seconds for $0.11. The economics are already proven in public.",
    stack: ["vision", "classify", "fetch", "store", "search", "voicein"],
    jev_role: "Scores the parsed ingredient list against each household rule and returns a verdict per rule with confidence, not a paragraph.",
    not_jev: "OCR of a curved foil packet in supermarket lighting is the actual hard problem.",
    phases: [
      { n: 1, name: "Read the label", detail: "Phone camera to OCR. Curved, glossy, low light. Budget most of your effort here.", caps: ["vision"] },
      { n: 2, name: "Parse", detail: "Ingredient string to a structured list. Additive codes, allergen aliases, sugar synonyms.", caps: ["classify"] },
      { n: 3, name: "Score", detail: "One typed call carrying every household rule at once. Adding a rule is nearly free.", caps: ["classify"] },
      { n: 4, name: "Backfill", detail: "Pre-score a catalogue overnight so the common products answer instantly from cache.", caps: ["fetch", "store"] },
      { n: 5, name: "Ask aloud", detail: "Hands full, trolley moving. Voice beats typing in an aisle.", caps: ["voicein"] },
    ],
    evidence: ["Scoring 3,000 kids’ snacks", "OCR-powered image classification", "Recipe scoring on five dimensions", "Instant calorie tracking"],
    hard_parts: [
      "OCR on real packaging is the whole game. The typed scoring is the easy half.",
      "Health claims carry liability. Show the rule that fired and the confidence, never a bare verdict.",
    ],
    effort: 3, impact: 5,
    moat: "The pre-scored product cache. It makes the app feel instant and it compounds.",
  },
  {
    id: "trip-assembler",
    category: "travel",
    name: "Constraint-first trip assembler",
    jtbd: "When I plan a trip with awkward constraints, I want options that already respect them, so I stop opening twenty tabs to rule things out.",
    who: "Families, accessibility needs, dietary needs, pet owners, long-haul workers.",
    why_now: "Booking sites filter on price and date. They cannot filter on 'step-free from the platform' or 'quiet room away from the lift'. That is a judgment over prose.",
    stack: ["browser", "domsnapshot", "fetch", "classify", "search", "textgen", "store", "guardrail"],
    jev_role: "Reads the messy prose of listings, amenities and reviews and returns a typed verdict per constraint. Also drives the browser agent action choice.",
    not_jev: "The browser harness, the search fan-out and the itinerary UI.",
    phases: [
      { n: 1, name: "Gather", detail: "Search APIs where they exist. A browser agent for the sites that have none.", caps: ["fetch", "browser", "domsnapshot"] },
      { n: 2, name: "Judge listings", detail: "One typed call per listing carrying every constraint. Noul per hard constraint, Score per soft one.", caps: ["classify"] },
      { n: 3, name: "Mine reviews", detail: "The truth about step-free access is in review prose, not the amenity list. Score each review.", caps: ["classify", "search"] },
      { n: 4, name: "Assemble", detail: "Compose the surviving options into whole itineraries and rank them.", caps: ["search", "textgen"] },
      { n: 5, name: "Stop before buying", detail: "Classify the action as irreversible and hand back to the human. Never auto-book.", caps: ["guardrail"] },
    ],
    evidence: ["A faster browser agent", "FlightWifi checks aircraft connectivity", "Vendor search by requirements", "A job crawler that matches your profile"],
    hard_parts: [
      "Booking sites fight automation. Expect breakage and design for it.",
      "Never let the agent complete a purchase. Classify risk in the same call as the action and stop at irreversible.",
      "Prices move while you deliberate. Re-verify before you show a final number.",
    ],
    effort: 5, impact: 5,
    moat: "The constraint vocabulary. Knowing which questions to ask is worth more than the scraping.",
  },
  {
    id: "inbox-operator",
    category: "comms",
    name: "Inbox that triages itself",
    jtbd: "When hundreds of messages arrive, I want them already sorted by what they need from me, so I only open the ones that need a person.",
    who: "Anyone with a support queue or a drowning inbox.",
    why_now: "Two shipped projects handled 63,000 and 1,500 emails. This is the single most proven pattern in the whole corpus.",
    stack: ["fetch", "classify", "store", "orchestrate", "search", "guardrail"],
    jev_role: "Intent, urgency, sentiment, and required action in one typed call per message. Confidence decides auto-file versus human.",
    not_jev: "Mail API auth, sync, threading, and the client.",
    phases: [
      { n: 1, name: "Pull", detail: "Mail API with incremental sync. Store the raw message beside every verdict.", caps: ["fetch", "store"] },
      { n: 2, name: "Judge", detail: "Intent Choice with a residual 'other', urgency Noul, frustration Score. One call.", caps: ["classify"] },
      { n: 3, name: "Route on confidence", detail: "High confidence auto-files. Low confidence goes to a review lane. Fit the threshold on labelled mail, do not guess it.", caps: ["guardrail"] },
      { n: 4, name: "Backfill history", detail: "Score the archive in a worker pool capped below the rate limit. This is where the 20 calls a second ceiling bites.", caps: ["orchestrate"] },
      { n: 5, name: "Search by meaning", detail: "Retrieve by intent, not keywords. 'The invoice dispute from March' should just work.", caps: ["search"] },
    ],
    evidence: ["Sorting 63,000 emails", "An inbox classifier for 1,500 emails", "Email classification and routing", "Search your inbox by intent"],
    hard_parts: [
      "Auto-archiving something important destroys trust permanently. Bias hard toward the review lane.",
      "63,000 messages at one call each is roughly 52 minutes of pure rate-limit floor. Plan the backfill as a batch job.",
    ],
    effort: 2, impact: 5,
    moat: "Your labelled corrections. They are what let you raise the auto-file threshold safely.",
  },
  {
    id: "applicant-matcher",
    category: "hiring",
    name: "Two-sided role and candidate matcher",
    jtbd: "When I apply or hire, I want the match judged on substance rather than keyword overlap, so neither side wastes a week.",
    who: "Job seekers, small teams without a recruiter.",
    why_now: "Keyword ATS matching is famously broken, and per-item judgment is now cheap enough to score every pairing.",
    stack: ["fetch", "browser", "classify", "search", "store", "textgen"],
    jev_role: "Scores each requirement against each candidate's evidence, and returns the gap list rather than a single number.",
    not_jev: "Crawling job boards, parsing CVs, and the application flow.",
    phases: [
      { n: 1, name: "Crawl roles", detail: "Job boards mostly resist APIs. A browser agent with a typed action space handles the awkward ones.", caps: ["fetch", "browser"] },
      { n: 2, name: "Structure both sides", detail: "Role to requirement list. CV to evidence list. Both typed, both stored.", caps: ["classify", "store"] },
      { n: 3, name: "Score the pairing", detail: "One call per requirement-evidence pair. Cheap enough to be exhaustive.", caps: ["classify"] },
      { n: 4, name: "Return the gap", detail: "The useful output is what is missing and whether it is learnable, not a percentage.", caps: ["textgen"] },
    ],
    evidence: ["Job and candidate matching", "A job crawler that matches your profile", "YouWare résumé screener", "Jevsume resume feedback"],
    hard_parts: [
      "Screening people is regulated and bias-prone. Log every judgment with its evidence and keep a human in the decision.",
      "Never let it auto-reject. Rank and explain only.",
    ],
    effort: 3, impact: 5,
    moat: "The requirement taxonomy per role family.",
  },
  {
    id: "intake-router",
    category: "health",
    name: "Clinic intake and triage router",
    jtbd: "When a patient describes a problem in their own words, I want it routed to the right clinician with the right urgency, so nothing serious waits behind something trivial.",
    who: "Small clinics and allied-health practices.",
    why_now: "Only two health projects exist in the corpus, and intake is the lowest-risk, highest-value slice of the category.",
    stack: ["classify", "voicein", "store", "guardrail", "realtime"],
    jev_role: "Urgency Score, department Choice, red-flag Nouls. The red flags are the point.",
    not_jev: "Scheduling, records, consent, and every compliance surface.",
    phases: [
      { n: 1, name: "Capture", detail: "A form that branches on what was already said. Voice for people who struggle to type.", caps: ["voicein"] },
      { n: 2, name: "Red flags first", detail: "A dedicated Noul per emergency symptom, evaluated in the same call. Any hit short-circuits to a human immediately.", caps: ["classify", "guardrail"] },
      { n: 3, name: "Route", detail: "Department Choice plus urgency Score. Low confidence always means a person looks.", caps: ["classify"] },
      { n: 4, name: "Hand off", detail: "Structured summary to the clinician, with the patient's own words preserved verbatim.", caps: ["store"] },
    ],
    evidence: ["A healthcare intake workflow prototype", "Live clinical-transcript classification prototype", "Incident triage in Box"],
    hard_parts: [
      "This is a safety-critical build. It must triage toward caution and never diagnose.",
      "Health data means real regulatory obligations before you write a line of code.",
      "The red-flag questions need clinical review. Do not author them alone.",
    ],
    effort: 4, impact: 5,
    moat: "Clinically reviewed red-flag questions.",
  },
  {
    id: "shelf-watch",
    category: "commerce",
    name: "Competitive shelf and price watcher",
    jtbd: "When I sell a product, I want to know when a competitor changes price, claims or positioning, so I can respond the same day.",
    who: "Small brands and marketplace sellers.",
    why_now: "Monitoring is a recurring check, which means a deterministic script, not a re-spawned agent. The judgment layer is the only part that needs a model.",
    stack: ["fetch", "browser", "classify", "store", "orchestrate", "vision"],
    jev_role: "Decides whether a detected change is materially meaningful, so you are alerted on repositioning and not on a whitespace edit.",
    not_jev: "Scheduling, diffing, storage, and alert delivery.",
    phases: [
      { n: 1, name: "Snapshot", detail: "Scheduled fetch of competitor pages. Embedded JSON first, browser only where needed.", caps: ["fetch", "browser", "orchestrate"] },
      { n: 2, name: "Diff", detail: "Plain deterministic diff. No model. Most days nothing changed.", caps: ["store"] },
      { n: 3, name: "Judge materiality", detail: "Only diffs get a typed call: is this material, which axis, how significant.", caps: ["classify"] },
      { n: 4, name: "Watch the imagery", detail: "Creative changes matter too. OCR the pack shot and compare claims.", caps: ["vision"] },
    ],
    evidence: ["Maxfusion competitor-ad research", "Ad account X-ray", "Bottally SEO and AEO audits", "News matching for brands"],
    hard_parts: [
      "Alert fatigue kills these products. The materiality judgment is the entire value.",
      "Only judge what actually changed, or you will burn the rate limit on unchanged pages.",
    ],
    effort: 2, impact: 4,
    moat: "The longitudinal history. Nobody can backfill last year's shelf.",
  },
  {
    id: "doc-backoffice",
    category: "backoffice",
    name: "Document pile to structured ledger",
    jtbd: "When a pile of invoices, receipts and statements arrives, I want them classified, extracted and filed, so month-end stops being manual.",
    who: "Small businesses, bookkeepers, solo operators.",
    why_now: "Four shipped projects cover the pieces. Nobody has assembled them into one back-office product.",
    stack: ["vision", "classify", "store", "orchestrate", "guardrail", "search"],
    jev_role: "Document type Choice, a routing decision for which extractor to run, and a confidence gate on every extracted figure.",
    not_jev: "OCR, the extractors, the ledger, and the accounting integration.",
    phases: [
      { n: 1, name: "Ingest", detail: "Email, scans, photos. Normalise everything to page images plus text.", caps: ["fetch", "vision"] },
      { n: 2, name: "Route per page", detail: "Typed call picks the document type and the extractor. Pages differ inside one PDF.", caps: ["classify"] },
      { n: 3, name: "Extract", detail: "Type-specific extraction. Deterministic where the layout is fixed.", caps: ["vision"] },
      { n: 4, name: "Gate the numbers", detail: "Money must never be silently wrong. Below threshold goes to human review.", caps: ["guardrail"] },
      { n: 5, name: "File and find", detail: "Ledger rows plus retrieval by meaning for audit questions.", caps: ["store", "search"] },
    ],
    evidence: ["Peakflo invoice coding", "Tax document classification", "A page-by-page OCR router", "Filling messy PDF forms"],
    hard_parts: [
      "A wrong figure in a ledger is worse than no figure. Gate hard and show the source crop.",
      "Document type varies page by page, so route per page and never per file.",
    ],
    effort: 3, impact: 4,
    moat: "Per-vendor layout memory. It compounds every month.",
  },
  {
    id: "review-gate",
    category: "devtools",
    name: "A review gate that reads the diff",
    jtbd: "When an agent or a teammate opens a pull request, I want the mechanical objections raised before a human looks, so review time goes on design rather than on catching the obvious.",
    who: "Anyone merging code an agent wrote.",
    why_now: "Twenty-six shipped projects are pipeline gates and they all found the same thing: adding a check is nearly free because every check rides in one call.",
    stack: ["classify", "guardrail", "store", "orchestrate"],
    jev_role: "Runs N independent checks over one diff in a single call and returns a typed verdict per check with confidence.",
    not_jev: "Git plumbing, the CI hook, and posting the comment.",
    phases: [
      { n: 1, name: "Get the diff", detail: "Per file, with enough surrounding context to judge. Skip lockfiles and generated output.", caps: ["fetch", "store"] },
      { n: 2, name: "Ask everything at once", detail: "One call carrying every rule as its own Noul or Score. Ten rules cost about what one costs.", caps: ["classify"] },
      { n: 3, name: "Gate on confidence", detail: "Block only on high-confidence failures. Everything else is a comment, not a veto.", caps: ["guardrail"] },
      { n: 4, name: "Track the false positives", detail: "A gate nobody trusts gets disabled. Log every override and retire rules that keep being wrong.", caps: ["store", "orchestrate"] }
    ],
    evidence: ["Fourteen checks for every pull request", "jev-codes", "A Jev code-review gate", "Plain-English code linting"],
    hard_parts: [
      "A noisy gate gets switched off within a week. Precision matters more than coverage.",
      "Rules written as prose drift. Keep them versioned beside the code they judge."
    ],
    effort: 1, impact: 4,
    moat: "The override log. It is the only honest measure of whether a rule earns its place."
  },
  {
    id: "npc-director",
    category: "games",
    name: "NPCs that decide instead of patrol",
    jtbd: "When a player meets a non-player character, I want it to choose plausibly against the current state, so encounters stop being a memorised patrol route.",
    who: "Game developers and simulation builders.",
    why_now: "Eighty-six control-loop projects exist and the frame budget is the whole constraint. A typed decision fits inside it; a generated sentence does not.",
    stack: ["classify", "realtime", "store"],
    jev_role: "Picks the next action from the moves that are legal right now, and returns the distribution so the character can be plausible instead of optimal.",
    not_jev: "The game loop, pathfinding, animation and state serialisation.",
    phases: [
      { n: 1, name: "Serialise the state", detail: "Compact text the model can read: positions, health, what the character can see. Keep it small.", caps: ["store"] },
      { n: 2, name: "Offer only legal moves", detail: "The code owns the menu. Never offer an action the engine cannot execute.", caps: ["classify"] },
      { n: 3, name: "Decide off the frame", detail: "Run the call asynchronously and keep acting on the last decision until the next lands.", caps: ["realtime"] },
      { n: 4, name: "Sample, do not maximise", detail: "Use the returned probabilities. Always taking the argmax makes a character that reads as a robot.", caps: ["classify"] }
    ],
    evidence: ["Directable video game NPCs", "Dungeon guards that change tactics", "The tactical sentinel", "Five hundred agents in a 3D environment"],
    hard_parts: [
      "A network call inside a frame budget will stall. Decide asynchronously or accept dropped frames.",
      "Perfect play is not fun. The distribution is the feature, not a defect to round away."
    ],
    effort: 3, impact: 2,
    moat: "None worth defending. Build it because it is the fastest way to learn the control loop."
  },
  {
    id: "feed-editor",
    category: "social",
    name: "A feed you actually wrote the rules for",
    jtbd: "When I open a feed, I want my own rules applied rather than the platform's, so I see what I came for.",
    who: "Anyone whose timeline has degraded.",
    why_now: "The most-repeated pattern in the corpus, with a dozen shipped variants. It is also the easiest credible thing to ship in a weekend.",
    stack: ["browser", "classify", "realtime", "store"],
    jev_role: "Scores each post against rules the user wrote in plain language, in the gap before they scroll past.",
    not_jev: "The extension, DOM observation, and the settings UI.",
    phases: [
      { n: 1, name: "Observe", detail: "MutationObserver on the feed container. Extract text per post as it appears.", caps: ["browser", "realtime"] },
      { n: 2, name: "Batch the visible", detail: "Judge the posts near the viewport, not the whole feed. Debounce scrolling.", caps: ["classify"] },
      { n: 3, name: "Act gently", detail: "Collapse and tag rather than delete. Always show what was hidden and why.", caps: ["realtime"] },
      { n: 4, name: "Cache verdicts", detail: "The same post reappears constantly. Cache by post id or you will pay repeatedly.", caps: ["store"] },
    ],
    evidence: ["An ad blocker with judgment", "Write your own X feed algorithm", "Filtering AI slop from YouTube", "A real-time feed quality filter"],
    hard_parts: [
      "Platform DOM changes without warning. Selector drift is your main maintenance cost.",
      "Judge only what is near the viewport, or one scroll burns hundreds of calls.",
      "Hiding the wrong post is invisible to the user. Make hidden items recoverable.",
    ],
    effort: 2, impact: 3,
    moat: "None. Ship it for the portfolio and the learning, not the defensibility.",
  },
];

export const BLUEPRINT_BY_CATEGORY = BLUEPRINTS.reduce((m, b) => {
  (m[b.category] ||= []).push(b.id);
  return m;
}, {});
