// gen-docs.mjs - emit docs/PATTERNS.md and docs/CAPABILITIES.md from the registries.
//
// These two files are GENERATED. Editing them by hand is pointless: the next
// build overwrites it. Change src/taxonomy.mjs or src/capabilities.mjs instead.
// Generating them is what stops the docs describing a capability the code lacks.

import fs from "node:fs";
import path from "node:path";
import { dirOf } from "./paths.mjs";
import { PATTERNS, FIELDS, FAMILIES, FAMILY_OF } from "./taxonomy.mjs";
import { CAPABILITIES } from "./capabilities.mjs";

const HERE = dirOf(import.meta.url);
const DOCS = path.join(HERE, "..", "docs");
const evidence = JSON.parse(fs.readFileSync(path.join(HERE, "..", "data", "evidence.json"), "utf8"));

const STAMP = "<!-- GENERATED by src/gen-docs.mjs - do not edit by hand. Edit the registry and re-run `npm run docs`. -->";
const count = (fn) => evidence.reduce((n, e) => n + (fn(e) ? 1 : 0), 0);
const esc = (s) => String(s).replace(/\|/g, "\\|");

/* ── PATTERNS.md ── */
const patRows = Object.entries(PATTERNS)
  .map(([k, p]) => ({ k, p, n: count((e) => e.pattern === k) }))
  .sort((a, b) => b.n - a.n);

let P = `${STAMP}\n\n# The 10 build patterns\n\n`;
P += `The ${evidence.length} shipped projects in this catalogue collapse into ten shapes. `;
P += `Scoring 3,000 snacks, sorting 63,000 emails and ranking 11 million videos are the same program with a different data source.\n\n`;
P += `Recognising which shape a new idea is saves rediscovering an architecture that already has a dozen worked examples.\n\n`;
P += `| Pattern | Projects | Difficulty | One line |\n|---|---:|:---:|---|\n`;
for (const { k, p, n } of patRows) {
  P += `| [${p.label}](#${k}) | ${n} | ${"●".repeat(p.difficulty)}${"○".repeat(5 - p.difficulty)} | ${esc(p.one_liner)} |\n`;
}
P += `\n---\n`;
for (const { k, p, n } of patRows) {
  const ex = evidence.filter((e) => e.pattern === k).sort((a, b) => b.impact - a.impact).slice(0, 6);
  const caps = {};
  evidence.filter((e) => e.pattern === k).forEach((e) => e.capabilities.forEach((c) => (caps[c] = (caps[c] || 0) + 1)));
  const topCaps = Object.entries(caps).sort((a, b) => b[1] - a[1]).slice(0, 6);
  const fields = {};
  evidence.filter((e) => e.pattern === k).forEach((e) => (fields[e.category] = (fields[e.category] || 0) + 1));
  const topFields = Object.entries(fields).sort((a, b) => b[1] - a[1]).slice(0, 5);

  P += `\n## ${p.label}\n<a id="${k}"></a>\n\n`;
  P += `**${esc(p.one_liner)}**\n\n`;
  P += `${p.n_note || ""}`;
  P += `| | |\n|---|---|\n`;
  P += `| Shape | \`${p.shape}\` |\n`;
  P += `| Projects | ${n} of ${evidence.length} |\n`;
  P += `| Difficulty | ${p.difficulty} of 5 |\n`;
  P += `| Commonest in | ${topFields.map(([f, c]) => `${FIELDS[f].label} (${c})`).join(", ")} |\n`;
  P += `| Usual capabilities | ${topCaps.map(([c]) => CAPABILITIES[c].label).join(", ")} |\n\n`;
  P += `**Why a typed model suits it.** ${esc(p.why_jev)}\n\n`;
  P += `**Shipped examples**\n\n`;
  for (const e of ex) P += `- [${esc(e.title)}](${e.url}) — ${esc(e.blurb.slice(0, 120))}\n`;
}

/* ── CAPABILITIES.md ── */
const capRows = Object.entries(CAPABILITIES)
  .map(([k, c]) => ({ k, c, n: count((e) => e.capabilities.includes(k)) }))
  .sort((a, b) => b.n - a.n);

let C = `${STAMP}\n\n# The 15 capabilities\n\n`;
C += `A capability is a **job to be done** inside a build, not a product. Typed classification is one of these. `;
C += `Keeping this layer provider-agnostic is what stops the catalogue dying when a vendor changes.\n\n`;
C += `Across the ${evidence.length} projects, the median build draws on about `;
C += `${Math.round(evidence.reduce((a, e) => a + e.capabilities.length, 0) / evidence.length)} of them.\n\n`;
C += `| Capability | Projects | Latency | Cost shape | Job |\n|---|---:|---|---|---|\n`;
for (const { k, c, n } of capRows) {
  C += `| [${c.label}](#${k}) | ${n} | ${c.latency} | ${c.cost_shape} | ${esc(c.job)} |\n`;
}
C += `\n---\n`;
for (const { k, c, n } of capRows) {
  const fam = {};
  evidence.filter((e) => e.capabilities.includes(k)).forEach((e) => {
    const f = FAMILY_OF[e.category]; fam[f] = (fam[f] || 0) + 1;
  });
  const topFam = Object.entries(fam).sort((a, b) => b[1] - a[1]).slice(0, 3);
  C += `\n## ${c.label}\n<a id="${k}"></a>\n\n`;
  C += `**${esc(c.job)}**\n\n`;
  C += `Used by **${n}** of ${evidence.length} projects`;
  if (topFam.length) C += `, most in ${topFam.map(([f, x]) => `${FAMILIES.find((y) => y.key === f).label} (${x})`).join(", ")}`;
  C += `. Typical latency ${c.latency}; billed ${c.cost_shape}.\n\n`;
  C += `| Provider | Kind | Notes |\n|---|---|---|\n`;
  for (const p of c.providers) {
    C += `| ${p.url ? `[${esc(p.name)}](${p.url})` : esc(p.name)} | ${p.kind} | ${esc(p.note)} |\n`;
  }
  if (c.gotcha) C += `\n> **Watch out.** ${esc(c.gotcha)}\n`;
}

fs.mkdirSync(DOCS, { recursive: true });
fs.writeFileSync(path.join(DOCS, "PATTERNS.md"), P);
fs.writeFileSync(path.join(DOCS, "CAPABILITIES.md"), C);
console.log(`DOCS OK  PATTERNS.md (${patRows.length} patterns)  CAPABILITIES.md (${capRows.length} capabilities)`);
